#include "explodingfake.h"

EXPLODING_FAKE_FOR(LightController_Off)
EXPLODING_FAKE_FOR(LightController_On)
EXPLODING_FAKE_FOR(TimeService_CancelPeriodicAlarm)
EXPLODING_FAKE_FOR(TimeService_DaysMatch)
EXPLODING_FAKE_FOR(TimeService_GetDay)
EXPLODING_FAKE_FOR(TimeService_GetMinute)
EXPLODING_FAKE_FOR(TimeService_SchedulePeriodicAlarm)
